### ISSUE TITLE
Write upload test thử đi em 

### ISSUE THREAD

**Issue by duykhanhrc** [ThaoUyenNguyen88/Herokuapp-Selenium#2]

**Comment by ThaoUyenNguyen88** [comment]
Em có viết rồi á anh

**Comment by duykhanhrc** [comment]
ok e, a thấy rồi, vậy framework của em đã có logger và report chưa, mỗi khi chạy xong sẽ sinh ra  1 log file đễ track lại nếu có issue.
Và 1 cái report để báo pass/failed testcase nào pass, nào failed á

**Comment by ThaoUyenNguyen88** [comment]
dạ chưa anh, để em làm ạ

**Comment by duykhanhrc** [comment]
Em có thể search 1 so keywork: Log4j và Extend report

**Comment by ThaoUyenNguyen88** [comment]
> Em có thể search 1 so keywork: Log4j và Extend report

sorry anh, mấy nay dự án bên em risk quá nên em hơi bận, em mới update code á anh, thanks anh

**Comment by duykhanhrc** [comment]
ok em, : ))) de a check thu
